<?php
/*
 *
 *  * Copyright (c) 2022.
 *  * Code by MUHAMMAD NASEER ASLAM.
 *  * You are not allowed to replicate my code as extension without permission.
 *  * If you need further help contact me on naseeraslamkhan016@gmail.com
 *
 */

/** @var $block Magento\Framework\View\Element\Template */
?>
<div id="shipping-plan" data-bind="scope: 'skuLookup'">
    <div id="sku-lookup">
        <!-- ko template: getTemplate()   --><!-- /ko -->
    </div>

</div>
<script type="text/x-magento-init">
{
    "#shipping-plan":{
          "Magento_Ui/js/core/app":<?= $block->getJsLayout() ?>
    }
}
</script>
